### ISSUE TITLE
Add social media links in the footer

### ISSUE THREAD

**Issue by junaidrahim** [DSC-KIIT/Hacken-Fest-2021#2]

**Comment by Shaleen-25** [comment]
@junaidrahim Hi, I would like to work on this issue, can you assign it to me and probably add few more details as to what exactly we're looking for here.

**Comment by junaidrahim** [comment]
Nothing super complicated. Just add these socials with icons on the footer. I have added some icons but they don't have any links on them. Would be cool if you can revamp and improve the footer a bit too. You can find more links to our socials on the website

- https://github.com/DSC-KIIT
- https://www.linkedin.com/company/dsckiit/
- https://dsckiit.in/
- https://medium.com/dsckiit

**Comment by Shaleen-25** [comment]
Hi @junaidrahim , raising a PR with this footer
<img width="1119" alt="Screenshot 2021-10-20 at 11 59 02 AM" src="https://user-images.githubusercontent.com/35434209/138039781-88d8066e-1961-4d9a-9d6c-ab3d15d21625.png">
This works right ?

**Comment by junaidrahim** [comment]
Yup, looks great

**Comment by sayannath** [comment]
> Hi @junaidrahim , raising a PR with this footer
> <img alt="Screenshot 2021-10-20 at 11 59 02 AM" width="1119" src="https://user-images.githubusercontent.com/35434209/138039781-88d8066e-1961-4d9a-9d6c-ab3d15d21625.png">
> This works right ?

Replace Praddyum Verma with my name because the lead has been changed.

```
+919874948947 (Sayan Nath)
```

**Comment by junaidrahim** [comment]
Closed by
- https://github.com/DSC-KIIT/Hacken-Fest-2021/pull/3
